/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SabiParlayPoolsInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BPS_DENOMINATOR"
      | "PICKS_MASK"
      | "RAKE_BPS"
      | "TIER_3_BPS"
      | "TIER_4_BPS"
      | "TIER_5_BPS"
      | "createMarket"
      | "getMarket"
      | "getTicket"
      | "markets"
      | "operator"
      | "owner"
      | "placeTicket"
      | "renounceOwnership"
      | "setOperator"
      | "setTreasury"
      | "settleAndPayout"
      | "ticketCount"
      | "tickets"
      | "transferOwnership"
      | "treasury"
      | "usdc"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "MarketCreated"
      | "MarketSettled"
      | "OrphanPoolSwept"
      | "OwnershipTransferred"
      | "PayoutDelivered"
      | "TicketPlaced"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BPS_DENOMINATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PICKS_MASK",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "RAKE_BPS", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "TIER_3_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TIER_4_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TIER_5_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createMarket",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMarket",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTicket",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "markets",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "operator", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "placeTicket",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setOperator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setTreasury",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "settleAndPayout",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish[],
      BigNumberish[],
      BigNumberish[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "ticketCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tickets",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "BPS_DENOMINATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "PICKS_MASK", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "RAKE_BPS", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "TIER_3_BPS", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "TIER_4_BPS", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "TIER_5_BPS", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getMarket", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getTicket", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "markets", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "operator", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "placeTicket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settleAndPayout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ticketCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tickets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
}

export namespace MarketCreatedEvent {
  export type InputTuple = [marketId: BigNumberish, locksAt: BigNumberish];
  export type OutputTuple = [marketId: bigint, locksAt: bigint];
  export interface OutputObject {
    marketId: bigint;
    locksAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketSettledEvent {
  export type InputTuple = [
    marketId: BigNumberish,
    resolution: BigNumberish,
    tier5Pool: BigNumberish,
    tier4Pool: BigNumberish,
    tier3Pool: BigNumberish
  ];
  export type OutputTuple = [
    marketId: bigint,
    resolution: bigint,
    tier5Pool: bigint,
    tier4Pool: bigint,
    tier3Pool: bigint
  ];
  export interface OutputObject {
    marketId: bigint;
    resolution: bigint;
    tier5Pool: bigint;
    tier4Pool: bigint;
    tier3Pool: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrphanPoolSweptEvent {
  export type InputTuple = [marketId: BigNumberish, amount: BigNumberish];
  export type OutputTuple = [marketId: bigint, amount: bigint];
  export interface OutputObject {
    marketId: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PayoutDeliveredEvent {
  export type InputTuple = [
    marketId: BigNumberish,
    ticketId: BigNumberish,
    user: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    marketId: bigint,
    ticketId: bigint,
    user: string,
    amount: bigint
  ];
  export interface OutputObject {
    marketId: bigint;
    ticketId: bigint;
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TicketPlacedEvent {
  export type InputTuple = [
    marketId: BigNumberish,
    ticketId: BigNumberish,
    user: AddressLike,
    stake: BigNumberish,
    picks: BigNumberish
  ];
  export type OutputTuple = [
    marketId: bigint,
    ticketId: bigint,
    user: string,
    stake: bigint,
    picks: bigint
  ];
  export interface OutputObject {
    marketId: bigint;
    ticketId: bigint;
    user: string;
    stake: bigint;
    picks: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SabiParlayPools extends BaseContract {
  connect(runner?: ContractRunner | null): SabiParlayPools;
  waitForDeployment(): Promise<this>;

  interface: SabiParlayPoolsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BPS_DENOMINATOR: TypedContractMethod<[], [bigint], "view">;

  PICKS_MASK: TypedContractMethod<[], [bigint], "view">;

  RAKE_BPS: TypedContractMethod<[], [bigint], "view">;

  TIER_3_BPS: TypedContractMethod<[], [bigint], "view">;

  TIER_4_BPS: TypedContractMethod<[], [bigint], "view">;

  TIER_5_BPS: TypedContractMethod<[], [bigint], "view">;

  createMarket: TypedContractMethod<
    [marketId: BigNumberish, locksAt: BigNumberish],
    [void],
    "nonpayable"
  >;

  getMarket: TypedContractMethod<
    [marketId: BigNumberish],
    [
      [
        bigint,
        bigint,
        boolean,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        locksAt: bigint;
        resolution: bigint;
        settled: boolean;
        grossPool: bigint;
        tier5Stakes: bigint;
        tier4Stakes: bigint;
        tier3Stakes: bigint;
        tier5Pool: bigint;
        tier4Pool: bigint;
        tier3Pool: bigint;
      }
    ],
    "view"
  >;

  getTicket: TypedContractMethod<
    [marketId: BigNumberish, ticketId: BigNumberish],
    [
      [string, bigint, bigint, boolean] & {
        user: string;
        stake: bigint;
        picks: bigint;
        paid: boolean;
      }
    ],
    "view"
  >;

  markets: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        boolean,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        locksAt: bigint;
        resolution: bigint;
        settled: boolean;
        grossPool: bigint;
        tier5Stakes: bigint;
        tier4Stakes: bigint;
        tier3Stakes: bigint;
        tier5Pool: bigint;
        tier4Pool: bigint;
        tier3Pool: bigint;
      }
    ],
    "view"
  >;

  operator: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  placeTicket: TypedContractMethod<
    [marketId: BigNumberish, picks: BigNumberish, stake: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setOperator: TypedContractMethod<[_op: AddressLike], [void], "nonpayable">;

  setTreasury: TypedContractMethod<[_t: AddressLike], [void], "nonpayable">;

  settleAndPayout: TypedContractMethod<
    [
      marketId: BigNumberish,
      resolution: BigNumberish,
      winnerTicketIds_5: BigNumberish[],
      winnerTicketIds_4: BigNumberish[],
      winnerTicketIds_3: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;

  ticketCount: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  tickets: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, bigint, bigint, boolean] & {
        user: string;
        stake: bigint;
        picks: bigint;
        paid: boolean;
      }
    ],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  treasury: TypedContractMethod<[], [string], "view">;

  usdc: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BPS_DENOMINATOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PICKS_MASK"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "RAKE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TIER_3_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TIER_4_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TIER_5_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createMarket"
  ): TypedContractMethod<
    [marketId: BigNumberish, locksAt: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getMarket"
  ): TypedContractMethod<
    [marketId: BigNumberish],
    [
      [
        bigint,
        bigint,
        boolean,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        locksAt: bigint;
        resolution: bigint;
        settled: boolean;
        grossPool: bigint;
        tier5Stakes: bigint;
        tier4Stakes: bigint;
        tier3Stakes: bigint;
        tier5Pool: bigint;
        tier4Pool: bigint;
        tier3Pool: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTicket"
  ): TypedContractMethod<
    [marketId: BigNumberish, ticketId: BigNumberish],
    [
      [string, bigint, bigint, boolean] & {
        user: string;
        stake: bigint;
        picks: bigint;
        paid: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "markets"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        boolean,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        locksAt: bigint;
        resolution: bigint;
        settled: boolean;
        grossPool: bigint;
        tier5Stakes: bigint;
        tier4Stakes: bigint;
        tier3Stakes: bigint;
        tier5Pool: bigint;
        tier4Pool: bigint;
        tier3Pool: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "operator"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "placeTicket"
  ): TypedContractMethod<
    [marketId: BigNumberish, picks: BigNumberish, stake: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setOperator"
  ): TypedContractMethod<[_op: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTreasury"
  ): TypedContractMethod<[_t: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "settleAndPayout"
  ): TypedContractMethod<
    [
      marketId: BigNumberish,
      resolution: BigNumberish,
      winnerTicketIds_5: BigNumberish[],
      winnerTicketIds_4: BigNumberish[],
      winnerTicketIds_3: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ticketCount"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "tickets"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, bigint, bigint, boolean] & {
        user: string;
        stake: bigint;
        picks: bigint;
        paid: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "MarketCreated"
  ): TypedContractEvent<
    MarketCreatedEvent.InputTuple,
    MarketCreatedEvent.OutputTuple,
    MarketCreatedEvent.OutputObject
  >;
  getEvent(
    key: "MarketSettled"
  ): TypedContractEvent<
    MarketSettledEvent.InputTuple,
    MarketSettledEvent.OutputTuple,
    MarketSettledEvent.OutputObject
  >;
  getEvent(
    key: "OrphanPoolSwept"
  ): TypedContractEvent<
    OrphanPoolSweptEvent.InputTuple,
    OrphanPoolSweptEvent.OutputTuple,
    OrphanPoolSweptEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PayoutDelivered"
  ): TypedContractEvent<
    PayoutDeliveredEvent.InputTuple,
    PayoutDeliveredEvent.OutputTuple,
    PayoutDeliveredEvent.OutputObject
  >;
  getEvent(
    key: "TicketPlaced"
  ): TypedContractEvent<
    TicketPlacedEvent.InputTuple,
    TicketPlacedEvent.OutputTuple,
    TicketPlacedEvent.OutputObject
  >;

  filters: {
    "MarketCreated(uint256,uint64)": TypedContractEvent<
      MarketCreatedEvent.InputTuple,
      MarketCreatedEvent.OutputTuple,
      MarketCreatedEvent.OutputObject
    >;
    MarketCreated: TypedContractEvent<
      MarketCreatedEvent.InputTuple,
      MarketCreatedEvent.OutputTuple,
      MarketCreatedEvent.OutputObject
    >;

    "MarketSettled(uint256,uint8,uint256,uint256,uint256)": TypedContractEvent<
      MarketSettledEvent.InputTuple,
      MarketSettledEvent.OutputTuple,
      MarketSettledEvent.OutputObject
    >;
    MarketSettled: TypedContractEvent<
      MarketSettledEvent.InputTuple,
      MarketSettledEvent.OutputTuple,
      MarketSettledEvent.OutputObject
    >;

    "OrphanPoolSwept(uint256,uint256)": TypedContractEvent<
      OrphanPoolSweptEvent.InputTuple,
      OrphanPoolSweptEvent.OutputTuple,
      OrphanPoolSweptEvent.OutputObject
    >;
    OrphanPoolSwept: TypedContractEvent<
      OrphanPoolSweptEvent.InputTuple,
      OrphanPoolSweptEvent.OutputTuple,
      OrphanPoolSweptEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PayoutDelivered(uint256,uint256,address,uint256)": TypedContractEvent<
      PayoutDeliveredEvent.InputTuple,
      PayoutDeliveredEvent.OutputTuple,
      PayoutDeliveredEvent.OutputObject
    >;
    PayoutDelivered: TypedContractEvent<
      PayoutDeliveredEvent.InputTuple,
      PayoutDeliveredEvent.OutputTuple,
      PayoutDeliveredEvent.OutputObject
    >;

    "TicketPlaced(uint256,uint256,address,uint256,uint8)": TypedContractEvent<
      TicketPlacedEvent.InputTuple,
      TicketPlacedEvent.OutputTuple,
      TicketPlacedEvent.OutputObject
    >;
    TicketPlaced: TypedContractEvent<
      TicketPlacedEvent.InputTuple,
      TicketPlacedEvent.OutputTuple,
      TicketPlacedEvent.OutputObject
    >;
  };
}
